Document: pcloudfs-gui
Title: Debian pcloudfs-gui Manual
Author: <insert document author here>
Abstract: This manual describes what pcloudfs-gui is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pcloudfs-gui/pcloudfs-gui.sgml.gz

Format: postscript
Files: /usr/share/doc/pcloudfs-gui/pcloudfs-gui.ps.gz

Format: text
Files: /usr/share/doc/pcloudfs-gui/pcloudfs-gui.text.gz

Format: HTML
Index: /usr/share/doc/pcloudfs-gui/html/index.html
Files: /usr/share/doc/pcloudfs-gui/html/*.html
